### PR TITLE
v1.6.0

### PR DESCRIPTION
**Pull request by ktwrd**
## Breaking Changes
- `musl` builds will be dropped since #19 was merged and fltk-sys doesn't have good enough support for `musl` builds, so `beans-rs` will be referencing `glibc` (whatever version that the `ubuntu-20.04` runner is using)

## Additions
- `fltk` will be used for dialogs to remove inconsistencies across systems. (#19)
  - `fltk` will never be used when the `--no-pause` flag is present.
- Added the ability to uninstall the targeted app (#29)
  - Game must be closed for this to work, and an error message will show to the user if the game is already open. Checked with; `crate::helper::is_game_running(String)`
- Added a progress bar for `.tar.zstd` extraction (#32)
  - **Note** The decompressed size is estimated since you cannot get the decompressed zstd size without actually decompressing it (afaik, please correct me if I'm wrong)
- Created specification for rustfmt (thx @toastxc for the help!)

### CODE REVIEW

**Comment by toastxc** [comment]
I'm happy to see musl go :3

**Comment by toastxc** [comment]
...It should be cleaned up a bit before merging
Mind if i?

**Comment by ktwrd** [comment]
> ...It should be cleaned up a bit before merging
> Mind if i?

Sure sounds good!

**Comment by ktwrd** [comment]
> I'm happy to see musl go :3 
> 

Same here, but I'm mainly concerned about server operators running weird distros that have ducky versions of glibc which works with the Source engine but not beans-rs

**Comment by toastxc** [comment]
We'll solve the edge cases when they appear ig.
retro-proofing is a fool's errand

**Comment by ktwrd** [comment]
#34 must be merged before this PR can be.

**Comment by ktwrd** [comment]
@toastxc merged #34, pls review and approve <3 /p

**Review by toastxc — APPROVED** [review]
looks pretty good! merging

**Pull request merged**
